version: '3.1'
services: 
  db: 
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
    - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/store_management_system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update